runtime: php
env: flex

runtime_config:
  document_root: public

skip_files: -.env

env_variables:
  APP_LOG: errorlog
  APP_DEBUG: true
  APP_KEY: base64:nqcZLQajthic3V12+C9o7kjDl2JQvcEKHj9HVC4/MtE=
  STORAGE_DIR: /tmp
  CACHE_DRIVER: database
  SESSION_DRIVER: database
  DB_CONNECTION: mysql
  DB_HOST: localhost
  DB_PORT: 3306
  DB_DATABASE: laravel
  DB_USERNAME: laravel
  DB_PASSWORD: laravel
  DB_SOCKET: "/cloudsql/glucos-app:us-central1:glucos"

beta_settings:
  cloud_sql_instances: "glucos-app:us-central1:glucos"
